---
name: Sync repo files
on:
  schedule:
    - cron: '44 17 * * *'
permissions:
  contents: read

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'prometheus'
    container:
      image: quay.io/prometheus/golang-builder
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: ./scripts/sync_repo_files.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PROMBOT_GITHUB_TOKEN }}
